apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twspostgres-pvc
  namespace: tws-three-tier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twspostgresqldeployment
  namespace: tws-three-tier
  labels:
    app: twspostgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twspostgresql
  template:
    metadata:
      labels:
        app: twspostgresql
    spec:
      containers:
      - name: twspostgresqlcontainer
        image: postgres:13-alpine
        env:
        - name: POSTGRES_DB
          value: "appdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: twspostgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: twspostgresqlservice
  namespace: tws-three-tier
spec:
  selector:
    app: twspostgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
