apiVersion: apps/v1
kind: Deployment
metadata:
  name: twsapideployment
  namespace: tws-three-tier
  labels:
    role: twsapi
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: twsapi
  template:
    metadata:
      labels:
        role: twsapi
    spec:
      containers:
      - name: twsapibackendcontainer
        image: twsbackend:1
        imagePullPolicy: Never
        env:
          - name: DB_TYPE
            value: "postgresql"
          - name: DB_HOST
            value: "twspostgresqlservice.tws-three-tier.svc.cluster.local"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "appdb"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: DB_SSL
            value: "false"
        ports:
        - containerPort: 3500
---
apiVersion: v1
kind: Service
metadata:
  name: twsapibackendservice
  namespace: tws-three-tier
spec:
  ports:
  - port: 3500
    protocol: TCP
    targetPort: 3500
  type: ClusterIP
  selector:
    role: twsapi
