apiVersion: apps/v1
kind: Deployment
metadata:
  name: twsfrontenddeployment
  namespace: tws-three-tier
  labels:
    role: twsfrontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: twsfrontend
  template:
    metadata:
      labels:
        role: twsfrontend
    spec: 
      containers:
      - name: twsfrontendcontainer
        image: twsfrontend:1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: twsfrontend-service  # Recommended naming convention
  namespace: tws-three-tier
  labels:
    role: twsfrontend
    env: demo
spec:
  type: NodePort  # Changed from ClusterIP for external access
  selector:
    role: twsfrontend  # Must match your Deployment's pod labels
  ports:
    - port: 81
      targetPort: 80
  type: NodePort
