
replicaCount: 1

image:
  repository: your-acr.azurecr.io/nginx
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3500
  targetPort: 3500

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: amanpathakdevops.study
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-backend-chart
              port:
                number: 3500
  tls: []



resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 300Mi

#livenessProbe:
#  httpGet:
 #   path: /
  #  port: 3000
#  initialDelaySeconds: 30
#  periodSeconds: 10

#readinessProbe:
#  httpGet:
 #   path: /
 #   port: 3000
 # initialDelaySeconds: 5
 # periodSeconds: 10

autoscaling:
  enabled: false

volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: azure-kv-provider

volumeMounts:
  - name: secrets-store-inline
    mountPath: /mnt/secrets-store
    readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}
