# secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: 6baabffd-464f-41cf-a940-c11eca500b3b
    keyvaultName: AceKeyVault2
    objects: |
      array:
        - |
          objectName: user
          objectType: secret
        - |
          objectName: password
          objectType: secret
    tenantId: 49dd1eb8-80a2-4006-bb3b-ccf13057f79a
