# secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: 1e266194-4afb-4d07-ae42-ad6c1e238811
    keyvaultName: AceKeyVault2
    objects: |
      array:
        - |
          objectName: name2
          objectType: secret
    tenantId: 49dd1eb8-80a2-4006-bb3b-ccf13057f79a
